apiVersion: v1
clusters:
- name: "k8s-ams-nl-appstore"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXakNDQVFHZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQVZNUk13RVFZRFZRUURFd3ByZFdKbGNtNWwKZEdWek1CNFhEVEkxTVRJd01qRXdORFl4TlZvWERUTTFNVEl3TWpFd05EWXhOVm93RlRFVE1CRUdBMVVFQXhNSwphM1ZpWlhKdVpYUmxjekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSkVjd3dGSGFYak1DaUtYClFYQ0kvQmozeEpCVkRLalZxS2Y2cVUyUkxocjY2VXRsbWFYdEFzODJrS3I1WHRiSmEwT2RqcjZoU25EdmlpSVMKc245ZHdTdWpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZApEZ1FXQkJTdVJTWGthbjExTHpYUkd5NlFDVi9hNzR6Zm5UQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQW9JMVBsCkY5RjZXYzZZQy9OOUV5VXZUaUttaE1SY0VZTGtuS3FtR0RRbjlnSWdRa1A4VmlncUpmVnFxVDQ2Wm9qSlA5VjIKb3R5SlhNRnI5YlFtU2ZOQjlLcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://955ef230-6be9-4eb2-bbd1-42a1426d47b0.api.k8s.nl-ams.scw.cloud:6443
contexts:
- name: admin@k8s-ams-nl-appstore
  context:
    cluster: "k8s-ams-nl-appstore"
    user: k8s-ams-nl-appstore-admin
current-context: admin@k8s-ams-nl-appstore
kind: Config
preferences: {}
users:
- name: k8s-ams-nl-appstore-admin
  user:
    token: 10cbb4ac-b08b-4043-b66a-c80f37316fa8